#!/bin/bash
set -euo pipefail

have_package() {
  grep -qE "^$1\$" <<< "${brew_ls_output}"
}

install_gpg() {
  if ! brew tap | grep -q homebrew/versions; then
    brew tap homebrew/versions
  fi

  if ! have_package gnupg21; then
    brew install gpgme
    brew unlink dirmngr gnupg2 gpg-agent gpgme
    brew install gnupg21
    brew link gpgme
  fi
}

install_mutt() {
  if ! have_package mutt; then
    brew install mutt --with-sidebar-patch --with-gpgme
  fi
}

main() {
  brew_ls_output="$(brew ls)" # global

  local pkg pkgs
  pkgs=()
  while read -r pkg; do
    if ! have_package "${pkg}"; then
      pkgs+=("${pkg}")
    fi
  done < ~/.setup/homebrew-packages

  # shellcheck disable=SC2086
  if [[ "${#pkgs[*]}" -ne 0 ]]; then
    echo "installing: ${pkgs[*]}"
    brew install ${pkgs[*]}
  fi

  install_gpg
  install_mutt
}
main "$@"
