#!/bin/bash

if [[ ! -d /opt/dev ]]; then
  >&2 "script only works if dev is around"
  exit 1
fi

if ! grep -q nix-darwin ~/.nix-channels; then
  echo "https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin" >> ~/.nix-channels
fi
export NIX_PATH=darwin=$HOME/.nix-defexpr/channels/darwin:$NIX_PATH

if ! grep -q home-manager ~/.nix-channels; then
  echo "https://github.com/rycee/home-manager/archive/f5c9303cedd67a57121f0cbe69b585fb74ba82d9.tar.gz home-manager" >> ~/.nix-channels
fi
export NIX_PATH=home-manager=$HOME/.nix-defexpr/channels/home-manager:$NIX_PATH

nix-channel --update
export NIX_PATH=darwin-config=/b/etc/nix/darwin.nix:$NIX_PATH
echo $NIX_PATH
nix-build '<darwin>' -A installer --out-link /tmp/nix-darwin && /tmp/nix-darwin/bin/darwin-installer
/run/current-system/sw/bin/darwin-rebuild switch
