task :default do

  lines = File.read('plugin_list').lines

  `mkdir -p bundle`

  threads = []
  lines.each do |line|
    threads << Thread.new {
      line = line.chomp
      unless line =~ /^#/
        repo = line.scan(%r{/([^/]+).git})[0][0]
        if Dir.exists?("bundle/#{repo}")
          puts "%% Pulling #{repo}\n"
          `cd ~/.vim/bundle/#{repo} ; git pull`
        else
          puts "%% Cloning #{repo}\n"
          `cd ~/.vim/bundle ; git clone #{line}`
        end
      end
    }
  end

  threads.map(&:join)

end

