task :default do

  lines = File.read('plugin_list').lines

  threads = []
  lines.each do |line|
    threads << Thread.new {
      line = line.chomp
      next if line =~ /^#/
      repo = line.scan(%r{/([^/]+).git})[0][0]
      if Dir.exists?("bundle/#{repo}")
        puts "%% Pulling #{repo}\n"
        `cd ~/.vim/bundle/#{repo} ; git pull`
      else
        puts "%% Cloning #{repo}\n"
        `cd ~/.vim/bundle ; git clone #{line}`
      end
    }
  end

  threads.map(&:join)

end
