task :default do

  lines = File.read('plugin_list').lines

  `mkdir -p bundle`

  threads = []
  lines.each do |line|
    threads << Thread.new {
      line = line.chomp
      next if line =~ /^#/
      repo = line.scan(%r{/([^/]+).git})[0][0]
      if Dir.exists?("bundle/#{repo}")
        puts "%% Pulling #{repo}\n"
        `cd ~/.vim/bundle/#{repo} ; git pull`
      else
        puts "%% Cloning #{repo}\n"
        `cd ~/.vim/bundle ; git clone #{line}`
      end
    }
  end

  threads.map(&:join)

  path = "bundle/vim-powerline/autoload/Powerline/Colorschemes/solarized.vim"
  if !File.exists?(path)
    puts "%% Installing powerline theme"
    `curl https://raw.github.com/gist/2003862/solarized.vim > #{path}`
  end

end

