#!/bin/bash
set -euo pipefail

dir="$(dirname "${BASH_SOURCE[0]}")"

mkdir -p "${dir}/bundle"

children=()

while read -r line; do
  if [[ "${line}" == "#"* || "${line}" == "" ]]; then
    continue
  fi

  (
    repo="$(basename "${line}" .git)"
    if [[ -d "${dir}/bundle/${repo}" ]]; then
      echo "%% Pulling ${repo}"
      ( cd "${dir}/bundle/${repo}" && git pull )
    else
      echo "%% Cloning ${repo}"
      ( cd "${dir}/bundle" && git clone "${line}" )
    fi
  ) &
  children+=($!)
done < "${dir}/plugin_list"

# shellcheck disable=SC2086
wait ${children[*]}
