#!/usr/bin/env ruby

SELF = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__

candidate = File.expand_path("../node_modules/.bin/mmdc", SELF)
if File.exist?(candidate)
  exec(candidate, *ARGV)
else
  exec(File.expand_path("../../.bin/mmdc", SELF))
end
