#!/usr/bin/env ruby

require 'open3'
require 'thread'
require 'fileutils'

require 'bundler/setup'

require 'json'
require 'github_api'

class Orgit # :nodoc:
  RemoteRepo = Struct.new(:name, :pushed_at, :default_branch)
  LocalRepo  = Struct.new(:name, :fetched_at, :ref)

  Repo = Struct.new(:name, :pushed_at, :fetched_at, :default_branch, :ref) do
    def needs_clone?;   pushed_at && !fetched_at end
    def needs_delete?; !pushed_at &&  fetched_at end
    def needs_fetch?;   pushed_at &&  fetched_at && fetched_at < pushed_at end
    def on_default_branch?; default_branch == ref end
  end

  class ParallelFetcher
    def initialize(path, threads = 10)
      @path = path
      @threads = threads
      @q = Queue.new
    end

    def run(repos)
      thrs = []
      @threads.times do
        thrs << Thread.new do
          while repo = @q.pop
            path = File.expand_path(repo.name, @path)
            if Dir.exist?(path)
              _, t = Open3.capture2e('git', '-C', path, 'fetch', 'origin', repo.default_branch)
            else
              _, t = Open3.capture2e('git', 'clone', "git@github.com:shopify/#{repo.name}", path)
            end
            if t.success?
              puts "\x1b[1;32m✓\x1b[0m #{repo.name} fetched"
            else
              puts "\x1b[1;31m✗\x1b[0m #{repo.name} fetch failed"
            end
          end
        end
      end

      repos.each { |r| @q << r }
      @q.close
      thrs.map(&:join)
    end
  end

  def initialize(path)
    @path = File.expand_path(path)
  end

  def local_repos
    @local_repos ||= gen_local_repo_list
  end
  
  def remote_repos
    @remote_repos ||= gen_remote_repo_list
  end

  def repos
    @repos ||= gen_repo_list
  end

  def missing_repos
    repos.select(&:needs_clone?)
  end

  def extra_repos
    repos.select(&:needs_delete?)
  end

  def repos_needing_update
    repos.select(&:needs_fetch?)
  end

  def delete_repo(repo)
    p = repo_path(repo)
    print "deleting #{p}..."
    STDOUT.flush
    FileUtils.rm_rf(repo_path(repo))
    puts ' done!'
  end

  def parallel_fetch(repos)
    ParallelFetcher.new(@path, 10).run(repos)
  end

  def checkout_latest(repo)
    unless repo.on_default_branch?
      puts "\x1b[1;31mrepo is on non-default branch and cannot be updated:\x1b[0m #{repo.name} (#{repo.ref} != #{repo.default_branch})"
      return
    end

    path = File.expand_path(repo.name, @path)

    fetch_head = File.read("#{path}/.git/FETCH_HEAD").split(/\s+/).first
    return if fetch_head.nil? # there are no commits

    head, t = Open3.capture2e('git', '-C', path, 'rev-parse', 'HEAD')
    head = t.success? ? head.chomp : ''

    return if head == fetch_head

    unless head.empty?
      o, t = Open3.capture2e('git', '-C', path, 'status', '--porcelain')
      if !t.success? || !o.chomp.empty?
        puts "cannot fast-forward repo with dirty working tree #{repo.name}"
        return
      end
      _, t = Open3.capture2e('git', '-C', path, 'merge-base', '--is-ancestor', head, fetch_head)
      unless t.success?
        puts "cannot fast-forward repo with unpushed commits #{repo.name}"
        return
      end
    end

    reset_repo(path, fetch_head)
  end

  def repo_dirty?(repo)
    path = File.expand_path(repo.name, @path)
    # o, t = Open3.capture2e('git', '-C', path, 'status', '--porcelain')
    o, t = Open3.capture2e('git', '-C', path, 'diff-index', '--quiet', 'HEAD', '--')
    !t.success? && o !~ /bad revision/
  end

  private

  def reset_repo(path, fetch_head)
    _, t = Open3.capture2e('git', '-C', path, 'reset', '--hard', fetch_head)
    raise "??? #{o} / #{args.inspect}" unless t.success?
  end

  def repo_path(repo)
    File.expand_path(repo.name, @path)
  end

  def gen_repo_list
    repos = {}
    local_repos.each do |lr|
      repos[lr.name] = Repo.new(lr.name, nil, lr.fetched_at, nil, lr.ref)
    end
    remote_repos.each do |rr|
      repos[rr.name] ||= Repo.new(rr.name, nil, nil, nil, nil)
      repos[rr.name].pushed_at = rr.pushed_at
      repos[rr.name].default_branch = rr.default_branch
    end
    repos.map { |_, v| v }
  end

  def gen_local_repo_list
    (Dir.entries(@path) - %w(. ..)).map do |name|
      path = File.expand_path(name, @path)
      next unless Dir.exist?(path) # skip .DS_Store and the like
      fetched_at = begin
        File.stat("#{path}/.git/FETCH_HEAD").mtime
      rescue Errno::ENOENT
        Time.at(0)
      end
      ref = begin
        head = File.read("#{path}/.git/HEAD").chomp
        head.scan(%r{ref: refs/heads/(.*)}).flatten.first || head
      rescue Errno::ENOENT
        nil
      end
      LocalRepo.new(name, fetched_at, ref)
    end.compact
  end

  def gen_remote_repo_list
    STDERR.print('retrieving repository list...')
    resp = github.repos.list(org: 'Shopify', per_page: 100)
    data = []
    resp.each_page do |page|
      STDERR.print('.')
      data.concat(page.map do |item|
        next if item['name'] == 'vault-mirror'
        RemoteRepo.new(item['name'], Time.parse(item['pushed_at']), item['default_branch'])
      end.compact)
    end
    STDERR.puts(' done!')
    data
  end

  def github
    @github ||= Github.new(oauth_token: oauth_token)
  end

  def oauth_token
    token, err, t = Open3.capture3(
      'security',
      'find-generic-password',
      '-w', # print only the password
      '-l', 'github-oauth-repo' 
    )
    raise "security find-generic-password failed: #{err}" unless t.success?
    token
  end
end

module CLI
  def self.run(*argv)
    case argv.shift
    when 'sync'
      CLI.sync(*argv)
    when 'dirty'
      CLI.dirty(*argv)
    else
      puts "usage: #$0 sync"
      exit 1
    end
  end

  def self.dirty(*argv)
    orgit = Orgit.new('~/src/github.com/shopify')
    q = Queue.new
    thrs = []
    10.times do
      thrs << Thread.new do
        while lr = q.pop
          puts(lr.name + "\n") if orgit.repo_dirty?(lr)
        end
      end
    end
    orgit.local_repos.each { |lr| q << lr }
    q.close
    thrs.map(&:join)
  end

  def self.sync(*argv)
    orgit = Orgit.new('~/src/github.com/shopify')

    if orgit.extra_repos.any?
      puts "found #{orgit.extra_repos} that don't exist on the remote."
    end
    orgit.extra_repos.each do |repo|
      puts "delete extra repo? (#{repo.name})"
      orgit.delete_repo(repo) if gets =~ /y/i
    end

    to_fetch = (orgit.missing_repos + orgit.repos_needing_update)
    puts "fetching #{to_fetch.size} repos..."
    orgit.parallel_fetch(to_fetch)

    orgit.repos.each do |repo|
      next if repo.needs_delete?
      orgit.checkout_latest(repo)
    end
  end
end

CLI.run(*ARGV)
