#!/bin/bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  >&2 echo "usage: $0 <file>"
  exit 1
fi

if [[ "$(pwd)" != ~ ]]; then
  >&2 echo "run from ~"
  exit 1
fi

if [[ ! -f "$1" ]]; then
  >&2 echo "arg must exist"
  exit 1
fi

if [[ "$1" == "~"* ]]; then
  >&2 echo "path must be relative from home"
  exit 1
fi

store_path="${HOME}/.dotfiles-src/eblob/${1//\//--}.gpg"

gpg \
  --output "${store_path}" \
  --encrypt \
  --recipient "burke@libbey.me" \
  "$1"
